@startuml
!theme plain
actor 环境 as enov
participant 传感器 as chuan
participant 单片机 as stc 
participant OLED显示屏 as OLED 
participant ESP8266 as esp 
participant WiFi路由器 as wifiap
actor 物联网平台 as iot 

stc -> chuan : 开始采样
chuan -> enov : 采集环境数据
enov -->> chuan : 环境数据
chuan -->> stc : 返回环境数据
stc ->> OLED : 发送环境数据
stc -> esp : 发送AT命令进入数据发送状态
esp -->> stc : OK
stc ->> esp : 发送MQTT数据报
esp ->> wifiap : 发送数据
wifiap ->> iot : 发送数据
stc ->> esp : 发送AT命令退出数据发送状态

@enduml