@startuml
!theme plain
package 串口通信{

usecase 串口初始化 as usrtinit 
usecase 串口中断 as uartInt

usecase 串口发送字节 as uartsendchar 
usecase 串口发送字符串 as uarrtsendstring
usecase 串口发送数组 as uartsendlen
}

uartsendchar <-- uarrtsendstring
uartsendchar <-- uartsendlen
@enduml