@startuml
!theme plain
left to right direction
skinparam actorStyle awesome


node 路由器 as wifiap

node 浏览器 as explore

package 感知层 {
node 单片机 as stc
node 传感器 as chuan 
node OLED显示屏 as OLED 
node ESP8266 as esp 
}


package 展示层 {
cloud 阿里云物联网平台 as iot 
node AMQP客户端 as amqpcli
database 数据库 as db
node 业务服务器 as sevicesever
}

stc -> OLED : IIC
stc --> esp : uart
chuan -> stc : GPIO

esp -> wifiap : \n\nwifi \n MQTT
wifiap -> iot : \nMQTT \n 上报数据

iot -> amqpcli : \n\n数据实时流转 \n AMQP\n\n\n\n
amqpcli -> db
db <--> sevicesever
sevicesever <--> explore : 业务api

@enduml